create first lab
M1shkaS/effective-web-course pull request #1
Opened 2022-10-27 04:17 UTC by M1shkaS

Селявин Михаил

2022-11-01 11:51 UTC, konstantinzelinsky commented
Для получения доп баллов за "git" необходимо поменять название ветки и PR
PR - [Lab 1] Add website markup (например)
ветка - feature/lab1

Для получения доп баллов за мобильную верстку требуются доработки
<img width="536" alt="image" src="https://user-images.githubusercontent.com/57330800/199225867-a2df8be2-b8b5-437e-be8c-67f2e053dfe1.png">

Стоит использовать форматтер (prettier)

На будущее:
- Это не было указано в требованиях, но стоит выносит, как минимум, цвета в переменные

Если без исправлений, то могу поставить 10 баллов

2022-11-01 11:52 UTC, konstantinzelinsky requested changes
Для получения доп баллов требуются доработки

2022-11-02 09:02 UTC, M1shkaS commented
Здравствуйте! Поменял название PR, но не знаю как поменять название ветки без её удаления. По поводу адаптива не знаю, что где подправить, когда я проверяю у меня всё хорошо. Готов принять 10 баллов.

![image](https://user-images.githubusercontent.com/108127550/199447516-23490e80-8949-4825-a4ce-2a676121fc7c.png)

2022-11-02 17:32 UTC, annamyamikova approved these changes
- Меню навигации не открывается
- [Чтобы переименовать ветку](https://git-scm.com/book/ru/v2/%D0%92%D0%B5%D1%82%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Git-%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8)
- Валидация идеально проходит
- Коммитов должны быть атомарны, и разбиты на логически функциональные части
- С у меня ок, только 

На что можно обратить внимание:
Директория с исходным кодом должна называться не dist, а src
Блок с grid сеткой своеобразно себя ведет, блок с изображением кроссовок сильно расстягивается

2022-11-02 17:32 UTC, annamyamikova commented on dist/css/media.css
> +      /* margin: 0; */
Не должно быть мертвого кода

2022-11-02 17:32 UTC, annamyamikova commented on dist/css/media.css
> +/* Pricing */
Перед комментарием лучше пустую строку ставить

2022-11-02 17:32 UTC, annamyamikova commented on dist/css/style.css
> +   color: #2D3436;
На будущее, цвета и шрифты лучше выносить в переменные

2022-11-02 17:33 UTC, annamyamikova commented
И да, лучше использовать prettier для стилей

2022-11-02 18:38 UTC, konstantinzelinsky commented
Окей, мержу, ставлю 10 баллов

2022-11-02 18:38 UTC, konstantinzelinsky approved these changes

2022-11-02 18:40 UTC, merged