[Lab 5] Add get posts and single Items by API and add search by nameStartWith
M1shkaS/effective-web-course pull request #6
Opened 2022-11-28 12:11 UTC by M1shkaS

Селявин Михаил

2022-11-30 17:53 UTC, annamyamikova requested changes
У тебя два lock файла - package-lock.json и yarn.lock. Нужно использовать только один пакетный менеджер.

Мне нужны значения VITE_API_KEY и VITE_BASE_API_URL, т.е. .env файл, так я никаких данных не получаю и вижу 404 ошибку сервера
Обычно .env.example файл оставляют в глобальном репозитории, а .env оставляют локально 

Не принято.

2022-12-01 03:05 UTC, M1shkaS commented
Добавил  .env.example  файл в котором хранятся  значения VITE_API_KEY и VITE_BASE_API_URL

2022-12-03 17:51 UTC, annamyamikova requested changes
<img width="1440" alt="Screenshot 2022-12-03 at 23 33 11" src="https://user-images.githubusercontent.com/37665408/205454685-a579b6de-0a2f-4575-abf9-aaea7d8968a0.png">
1. Почему-то у тебя ссылка на связующие сущности ведет не туда. Так не должно быть
2. Если ввести в поисковике какие-то слова, а потом стереть и нажать поиск, то не ищет все элементы, запрос не проходит

Не принято.

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/header/Header.modules.scss
> +.toggle__checkbox {
Нет необходимости использовать БЭМ и его производные в компонентном подходе реакта
Ты в каждом компоненте можешь писать один и тот же класс .Checkbox, например, потому что в итоговом dom дереве у тебя они будут разные. Для каждого компонента класс будет таким .Checkbox_{хеш}

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/header/Header.modules.scss
> +label:has(.toggle__checkbox:checked) .star__wrapper {
Здесь лучше использовать вложеенность

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/header/Header.tsx
> +            className="toggle__checkbox"
В импортах пишут так
`import classes from './Header.module.scss';`

А здесь на этой строке будет так:
`className={classes.Checkbox}`

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/linksCreation/LinksCreation.tsx
> +function renderList(list: ArrayLinksCreation[]) {
Плохая практика использовать function declaration из-за "поднятия"
Лучше использовать стрелочные функции

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/searchForm/Searchform.modules.scss
> +    background-color: var(--button-background-color);
В scss есть свой способ использования переменных. Этот способ устаревший

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/searchForm/Searchform.modules.scss
> +  &__button:hover {
Лучше использовать вложенность

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/spinner/Spinner.modules.scss
> +.windows8 #wBall_1 {
Не используй id-шники, пожалуйста

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/components/spinner/Spinner.tsx
> +export default Spinner;
Папки компонетов, также как и сами компоненты, называются с большой буквы

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/routes/charactersPage/CharactersPage.tsx
> +const CharactersPage = observer(() => {
метод observer нужно использовать в конце компонента. Пример:
`export default observer(CharactersPage);`

2022-12-03 17:51 UTC, annamyamikova commented on marvel/src/routes/charactersPage/CharactersPage.tsx
> +          {`(${totalPosts})`}
Достаточно написать `{totalPosts}`

2022-12-05 03:45 UTC, M1shkaS commented
Всё исправил

2022-12-10 07:06 UTC, konstantinzelinsky commented
Привет, у меня не работает проект из-за ошибок линтера. 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/57330800/206836672-9b2590a9-c128-45c0-ac55-0a2c86cfa4f5.png">

Когда меняешь название папок с одного регистра на другой гит может это не воспринять. Поменяй, пожалуйста, прям в гитхабе

2022-12-10 07:06 UTC, konstantinzelinsky requested changes
Проблемы с линтером

2022-12-10 09:17 UTC, M1shkaS commented
Всё исправил

2022-12-11 08:46 UTC, konstantinzelinsky approved these changes
Принял. Так как там были некоторые недоработки, когда проверяла Аня, балл не максимальный

2022-12-11 08:46 UTC, konstantinzelinsky commented on marvel/src/components/SearchForm/SearchForm.tsx
> +  const { getPostsByNameStartsWith, getPostsByTitleStartsWith, getPostsList } =
Обычно функции не деструктуризуют. Просто используют так store.someFunctin()

2022-12-11 08:46 UTC, merged